name: API Test Suite

# ───────────────────────────── Triggers ─────────────────────────────
on:
  push:
    branches: [ master ]          # or 'main'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# ───────────────────────────── Job matrix ───────────────────────────
jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30           

    env:
      API_BASEURL : ${{ secrets.API_BASEURL }}
      API_USERNAME: ${{ secrets.API_USERNAME }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}

    steps:

      # ---------- Source ----------
      - name: Checkout source
        uses: actions/checkout@v3

      # ---------- Cache ----------
      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key : ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # ---------- JDK ----------
      - name: ☕ Set up Temurin 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven            

      # ---------- Tests + Allure results ----------
      - name: Run API tests
        run: |
          mvn -B -ntp -T1C \
              -Dapi.baseUrl="$API_BASEURL" \
              -Dapi.username="$API_USERNAME" \
              -Dapi.password="$API_PASSWORD" \
              -Dapi.timeout=10 \
              -Dretry.count=2 \
              clean test                \
              allure:report             

      # ---------- Artifacts ----------
      - name: Upload Allure HTML
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
